/*
 * Filename: swc_clock.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component representing the functionality of the clock
 * name: swc_Clock
 * shortname: Clock
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_clock.h"



/* USER CODE START SWC_CLOCK_INCLUDE */
#include "green_LED.h"
#include "red_LED.h"
#include "yellow_LED.h"
/* USER CODE END SWC_CLOCK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CLOCK_USERDEFINITIONS */
uint8_t g_hours = 0;
uint8_t g_minutes = 0;
/* USER CODE END SWC_CLOCK_USERDEFINITIONS */



/*
 * component: swc_Clock
 * cycletime: 50
 * description: Runnable
 * events: 
 * name: CLOCK_input_run
 * shortname: input
 * signalIN: 
 * signalOUT: so_event
 * task: tsk_io
 */
void CLOCK_input_run(RTE_event ev){
	
	/* USER CODE START CLOCK_input_run */
    RTE_SC_EVENT_pullPort(&SO_EVENT_signal);
    /* USER CODE END CLOCK_input_run */
}

/*
 * component: swc_Clock
 * cycletime: 0
 * description: Statemachine runnable
 * events: ev_event_onData
 * name: CLOCK_contol_run
 * shortname: contol
 * signalIN: so_event
 * signalOUT: so_displayData
 * task: tsk_control
 */
void CLOCK_contol_run(RTE_event ev){
	
	/* USER CODE START CLOCK_contol_run */
    SC_EVENT_data_t data = RTE_SC_EVENT_get(&SO_EVENT_signal);
    static ClockContainerState containerState = CLOCK_C_ISDISPLAYING;
    
    CONTAINER_processEvent(&containerState, data.m_ev);       
    /* USER CODE END CLOCK_contol_run */
}

/*
 * component: swc_Clock
 * cycletime: 250
 * description: TFT display runnable
 * events: 
 * name: CLOCK_display_run
 * shortname: display
 * signalIN: so_displayData
 * signalOUT: 
 * task: tsk_io
 */
void CLOCK_display_run(RTE_event ev) {
    /* USER CODE START CLOCK_display_run */
    static uint8_t last_hour = 255;
    static uint8_t last_minute = 255;
    static boolean_t last_invHours = FALSE;
    static boolean_t last_invMinutes = FALSE;
    static boolean_t show_colon = TRUE;

    uint8_t hour = g_hours;
    uint8_t minute = g_minutes;

    SC_DISPLAYDATA_data_t data = RTE_SC_DISPLAYDATA_get(&SO_DISPLAYDATA_signal);

    // Configuration
    TFT_setTextSize(4);
    TFT_setFont(NULL);
    TFT_setTextWrap(0);

    // Coordinate calculation only once
    static int16_t x_hour, y_hour, x_colon, y_colon, x_minute, y_minute;
    static boolean_t pos_calculated = FALSE;

    if (!pos_calculated) {
        char hourStr[] = "88";
        char colonStr[] = ":";
        char minStr[] = "88";

        int16_t x1, y1;
        uint16_t w_h, w_c, w_m, h;

        TFT_getTextBounds(hourStr, 0, 0, &x1, &y1, &w_h, &h);
        TFT_getTextBounds(colonStr, 0, 0, &x1, &y1, &w_c, &h);
        TFT_getTextBounds(minStr, 0, 0, &x1, &y1, &w_m, &h);

        int total_w = w_h + w_c + w_m;
        int base_x = (CFG_TFT_WIDTH - total_w) / 2;
        int base_y = (CFG_TFT_HEIGHT - h) / 2;

        x_hour = base_x;
        x_colon = x_hour + w_h;
        x_minute = x_colon + w_c;

        y_hour = y_colon = y_minute = base_y;

        pos_calculated = TRUE;
    }

    // === Update hour display if time or inversion changed ===
    if (hour != last_hour || data.invHours != last_invHours) {
        last_hour = hour;
        last_invHours = data.invHours;

        char hourStr[3];
        sprintf(hourStr, "%02d", hour);

        if (data.invHours) {
            TFT_setColors(BLACK, WHITE);
        } else {
            TFT_setColors(WHITE, BLACK);
        }

        TFT_setCursor(x_hour, y_hour);
        TFT_print(hourStr);
    }

    // === Update minute display if time or inversion changed ===
    if (minute != last_minute || data.invMinutes != last_invMinutes) {
        last_minute = minute;
        last_invMinutes = data.invMinutes;

        char minStr[3];
        sprintf(minStr, "%02d", minute);

        if (data.invMinutes) {
            TFT_setColors(BLACK, WHITE);
        } else {
            TFT_setColors(WHITE, BLACK);
        }

        TFT_setCursor(x_minute, y_minute);
        TFT_print(minStr);
    }

    // === Always toggle colon ===
    char colonStr[2];
    sprintf(colonStr, show_colon ? ":" : " ");

    TFT_setColors(WHITE, BLACK);
    TFT_setCursor(x_colon, y_colon);
    TFT_print(colonStr);

    show_colon = !show_colon;
    /* USER CODE END CLOCK_display_run */
}


/* USER CODE START SWC_CLOCK_FUNCTIONS */

/* USER CODE END SWC_CLOCK_FUNCTIONS */

