
/*
 * Filename: swc_clock.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Software component representing the functionality of the clock
 */

#ifndef _H_DEFINE_SWC_CLOCK
#define _H_DEFINE_SWC_CLOCK

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_CLOCK_INCLUDES */
#include "clock_container.h"
#include "tft.h"
/* USER CODE END SWC_CLOCK_INCLUDES */



/* USER CODE START SWC_CLOCK_USERDEFINITIONS */
extern uint8_t g_hours;
extern uint8_t g_minutes;
/* USER CODE END SWC_CLOCK_USERDEFINITIONS */


/*
 * component: swc_Clock
 * cycletime: 50
 * description: Runnable
 * events: 
 * name: CLOCK_input_run
 * shortname: input
 * signalIN: 
 * signalOUT: so_event
 * task: tsk_io
 */
void CLOCK_input_run(RTE_event ev);

/*
 * component: swc_Clock
 * cycletime: 0
 * description: Statemachine runnable
 * events: ev_event_onData
 * name: CLOCK_contol_run
 * shortname: contol
 * signalIN: so_event
 * signalOUT: so_displayData
 * task: tsk_control
 */
void CLOCK_contol_run(RTE_event ev);

/*
 * component: swc_Clock
 * cycletime: 250
 * description: TFT display runnable
 * events: 
 * name: CLOCK_display_run
 * shortname: display
 * signalIN: so_displayData
 * signalOUT: 
 * task: tsk_io
 */
void CLOCK_display_run(RTE_event ev);


#endif