/*
 * Filename: sc_displaydata_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass
 * name: sc_displayData
 * shortname: displayData
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_displaydata_type.h"



/* USER CODE START SC_DISPLAYDATA_INCLUDE */

/* USER CODE END SC_DISPLAYDATA_INCLUDE */




/* USER CODE START SC_DISPLAYDATA_USERDEFINITIONS */

/* USER CODE END SC_DISPLAYDATA_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_DISPLAYDATA signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_DISPLAYDATA_driverIn(SC_DISPLAYDATA_data_t *const data)
{
	/* USER CODE START driverInSC_DISPLAYDATA */
    
	return RC_SUCCESS;
	/* USER CODE END driverInSC_DISPLAYDATA */
}
/**
 * Default OUT driver API
 */
inline RC_t SC_DISPLAYDATA_driverOut(const SC_DISPLAYDATA_data_t  *const data)
{
	/* USER CODE START driverOutSC_DISPLAYDATA */

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_DISPLAYDATA */
}



