
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: The common gloabl signal pool, all signals will be stored here.
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */
/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_event.h"
#include "sc_displaydata.h"



/*
 * description: A Signal
 * indriver: default
 * name: so_event
 * onDataError: 0
 * onDataUpdate: ev_event_onData
 * outdriver: default
 * resource: None
 * shortname: event
 * signalclass: sc_event
 * signalpool: sp_common
 */
extern SC_EVENT_t SO_EVENT_signal;


/*
 * description: A Signal
 * indriver: default
 * name: so_displayData
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: displayData
 * signalclass: sc_displayData
 * signalpool: sp_common
 */
extern SC_DISPLAYDATA_t SO_DISPLAYDATA_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif