/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: The common gloabl signal pool, all signals will be stored here.
 * endaddr: ADR_SP_COMMON_END
 * name: sp_common
 * shortname: common
 * startaddr: ADR_SP_COMMON_START
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_event.h"
#include "sc_event_type.h"
#include "sc_displaydata.h"
#include "sc_displaydata_type.h"



/* signal configuration */
/*
 * description: A Signal
 * indriver: default
 * name: so_event
 * onDataError: 0
 * onDataUpdate: ev_event_onData
 * outdriver: default
 * resource: None
 * shortname: event
 * signalclass: sc_event
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_event_updTasks = { tsk_control };
 

static const SC_EVENT_cfg_t SO_EVENT_cfg = 
{
   /* indriver           */  SC_EVENT_driverIn,
   /* outdriver          */  SC_EVENT_driverOut,

   /* onUpdate           */  ev_event_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_event_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_event */


/* signal data */

SC_EVENT_t SO_EVENT_signal= 
{
   /* init value    */  SC_EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_cfg,
}; /* data so_event */

/* signal configuration */
/*
 * description: A Signal
 * indriver: default
 * name: so_displayData
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: displayData
 * signalclass: sc_displayData
 * signalpool: sp_common
 */

 

static const SC_DISPLAYDATA_cfg_t SO_DISPLAYDATA_cfg = 
{
   /* indriver           */  SC_DISPLAYDATA_driverIn,
   /* outdriver          */  SC_DISPLAYDATA_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_displaydata */


/* signal data */

SC_DISPLAYDATA_t SO_DISPLAYDATA_signal= 
{
   /* init value    */  SC_DISPLAYDATA_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DISPLAYDATA_cfg,
}; /* data so_displaydata */



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_EVENT_incAge( &SO_EVENT_signal, tick); 
   RTE_SC_DISPLAYDATA_incAge( &SO_DISPLAYDATA_signal, tick); 
   
}

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common(){
   RTE_SC_EVENT_init( &SO_EVENT_signal); 
   RTE_SC_DISPLAYDATA_init( &SO_DISPLAYDATA_signal); 
   
}		


